Fix so that visiting http://localhost:8080/results/Workspaces.gump does not result in
org.hibernate.MappingException: Resource: org/apache/gump/dynagump/database/hibernate/HostsHib.hbm.xml not found
        at org.hibernate.cfg.Configuration.addResource(Configuration.java:479)
        at org.hibernate.cfg.Configuration.parseMappingElement(Configuration.java:1465)

(using vanilla maven 2.0.2 and instructions from README.txt).