Fix testcase error introduced in builder.py.
* pygump/python/gump/plugins/builder.py: commenting out this existence test makes the associated testcase fail under posix. Error log:

======================================================================
FAIL: test_do_script (testPluginBuilder.BuilderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File /home/gump3/Gump3/gump/test/testPluginBuilder.py, line 66, in test_do_script
AssertionError: Error not raised

----------------------------------------------------------------------